# Generated by Django 2.1 on 2018-12-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialApp', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='CEO',
        ),
    ]
