# Generated by Django 2.1 on 2018-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialApp', '0003_remove_company_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
