# Generated by Django 2.1 on 2018-12-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialApp', '0004_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
